import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/lib/react-query-provider";
import { ThemeProvider } from "@/context/themeContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  dark:bg-gray-500`}
      >
        <ReactQueryProvider>
          {/* <BoardContextProvider> */}
          {/* You can place this wherever you want the button */}
          <ThemeProvider>{children}</ThemeProvider>
          {/* </BoardContextProvider> */}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
