import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/lib/react-query-provider";
import { ThemeProvider } from "next-themes";
import { SocketProvider } from "@/context/socketContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <SocketProvider>
            <ThemeProvider
              attribute="class"
              enableSystem={false}
              defaultTheme="light"
              storageKey="theme"
            >
              {children}
            </ThemeProvider>
          </SocketProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
